dubbo:
#声明注册到zk的名字 应该程序的名称
  application:
    name: boot-ego-user-service-provider
#声明注册中心的地址和方式
  registry:
    address: zookeeper://47.115.46.193:2181
    timeout: 100000
  #使用dubbo协议，将服务暴露在20880端口
  protocol:
    name: dubbo
    port: 20880
  provider:
    timeout: 100000
  config-center:
    timeout: 100000


